### ISSUE TITLE
GRU object has no attribute weight

### ISSUE THREAD

**Issue by fvanclef** [cxhernandez/molencoder#8] opened 2017-07-25 12:53 UTC
Hello, 

I tried to train the model but I got this error 

Traceback (most recent call last):
  File "/opt/anaconda3/bin/molencoder", line 9, in <module>
    load_entry_point('molencoder==0.1a0', 'console_scripts', 'molencoder')()
  File "/opt/anaconda3/lib/python3.5/site-packages/molencoder-0.1a0-py3.5.egg/molencoder/cli/main.py", line 32, in main
  File "/opt/anaconda3/lib/python3.5/site-packages/molencoder-0.1a0-py3.5.egg/molencoder/cli/main.py", line 37, in args_func
  File "/opt/anaconda3/lib/python3.5/site-packages/molencoder-0.1a0-py3.5.egg/molencoder/cli/parser_train.py", line 31, in func
  File "/opt/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 136, in apply
    module.apply(fn)
  File "/opt/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 137, in apply
    fn(self)
  File "/opt/anaconda3/lib/python3.5/site-packages/molencoder-0.1a0-py3.5.egg/molencoder/utils.py", line 180, in initialize_weights
  File "/opt/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 238, in __getattr__
    type(self).__name__, name))
AttributeError: 'GRU' object has no attribute 'weight'

I had to install pytorch via the conda install. The version is pytorch-0.1.12 and I am using python 3.5.2.

Thanks

**Comment by cxhernandez** [comment] 2017-07-25 16:52
Thanks for the report! I was able to reproduce the error— will investigate now.

**Comment by cxhernandez** [comment] 2017-07-25 17:32
fixed in #10. Turns out `GRU.weight` was changed to `GRU.all_weights` in PyTorch 0.1.12

**Closed as completed by cxhernandez** 2017-07-25 17:32 UTC

**Comment by fvanclef** [comment] 2017-07-26 07:21
Great, it is working now!

Thanks

Nb: I had to replace yaml by PyYaml in the requirements.txt otherwise the installation failed.

Searching for yaml
Reading https://pypi.python.org/simple/yaml/

error: Could not find suitable distribution for Requirement.parse('yaml')
